import { writeFile } from 'node:fs/promises';
import { POSE_TABLE } from './pose-table.mjs';
import { BONES, PART_PARENTS, THICKNESS } from './rig-spec.mjs';

/**
 * Emit the pose table into the runtime as TypeScript.
 *
 * One source of truth: the same angles that drew the character sheet drive the
 * rig in the game. If these ever diverged, the sheet would stop describing the
 * character that actually ships.
 */
const KEYS = [
  'lean', 'head', 'hipX', 'hipY',
  'frontArm', 'frontForearm', 'backArm', 'backForearm',
  'frontThigh', 'frontShin', 'backThigh', 'backShin',
  'braidSweep', 'sashSweep',
];

export async function emitPoses(file) {
  const entries = Object.entries(POSE_TABLE).map(([name, pose]) => {
    const fields = KEYS
      .map((key) => `    ${key}: ${String(pose[key] ?? 0)},`)
      .join('\n');
    return `  ${name}: {\n${fields}\n  },`;
  });

  const source = `/**
 * Generated by \`npm run sprites:mim\` from \`scripts/mim/pose-table.mjs\`.
 * Do not edit by hand — edit the pose table and regenerate.
 *
 * Angles are degrees, clockwise, with 0 pointing down the screen.
 * \`braidSweep\` and \`sashSweep\` are radians of trail rotation.
 */

export interface MimPoseAngles {
  readonly lean: number;
  readonly head: number;
  readonly hipX: number;
  readonly hipY: number;
  readonly frontArm: number;
  readonly frontForearm: number;
  readonly backArm: number;
  readonly backForearm: number;
  readonly frontThigh: number;
  readonly frontShin: number;
  readonly backThigh: number;
  readonly backShin: number;
  readonly braidSweep: number;
  readonly sashSweep: number;
}

export const MIM_POSES = {
${entries.join('\n')}
} as const satisfies Readonly<Record<string, MimPoseAngles>>;

export type MimPoseName = keyof typeof MIM_POSES;

/** Bone lengths in source pixels, for anything that has to measure the body. */
export const MIM_BONES = ${JSON.stringify(BONES)} as const;
export const MIM_LIMB_THICKNESS = ${JSON.stringify(THICKNESS)} as const;
export const MIM_PART_PARENTS = ${JSON.stringify(PART_PARENTS, null, 2)} as const;
`;
  await writeFile(file, source, 'utf8');
  return Object.keys(POSE_TABLE).length;
}
