export const TICKS_PER_SECOND = 60;
export const FIXED_STEP_SECONDS = 1 / TICKS_PER_SECOND;

export const balanceConfig = {
  arenaWidth: 960,
  arenaHeight: 540,
  groundY: 450,
  fighterRadius: 38,
  walkSpeed: 250,
  airMoveSpeed: 335,
  crouchSpeed: 95,
  dashSpeed: 510,
  dashDurationTicks: 10,
  doubleTapWindow: 13,
  simultaneousInputWindow: 2,
  inputBufferWindow: 12,
  comboContinuationWindow: 24,
  autoComboDamageScale: 0.88,
  preciseBlockWindowFrames: 5,
  perfectBlockWindowFrames: 2,
  preciseBlockStunMultiplier: 0.35,
  preciseBlockGaugeMultiplier: 0.12,
  perfectBlockAdvantageFrames: 3,
  defenseFeedbackFrames: 45,
  defenseEffectFrames: 18,
  reversalWindow: 3,
  comboEscapeDelayFrames: 3,
  comboEscapeWindowFrames: 3,
  comboEscapeFailureCooldownFrames: 45,
  comboBreakWindowFrames: 12,
  grabRange: 88,
  comboBreakSegmentCost: 1,
  maxDefenseSegments: 2,
  comboBreakKnockbackSpeed: 420,
  comboEscapeNeutralDistance: 210,
  reversalCost: 35,
  jumpSpeed: 720,
  gravity: 1_650,
  maxHealth: 100,
  maxEnergy: 100,
  maxBlockMeter: 100,
  blockRecoveryPerTick: 0.18,
  knockdownTicks: 42,
  wakeupTicks: 24,
  comboTimeoutTicks: 90,
  roundSeconds: 90,
  countdownTicks: TICKS_PER_SECOND * 3 + 45,
  roundOverTicks: TICKS_PER_SECOND * 2,
  roundsToWin: 2,
} as const;
