export const CHARACTER_ANIMATION_STATES = [
  'idle',
  'walk',
  'dash-start',
  'dash',
  'dash-whiff',
  'jump-start',
  'jump-rise',
  'jump-fall',
  'landing',
  'crouch',
  'block',
  'precise-block',
  'perfect-block',
  'light-1',
  'light-2',
  'light-3',
  'heavy-1',
  'heavy-2',
  'heavy-3',
  'low-light',
  'low-heavy',
  'air-light',
  'air-heavy',
  'grab',
  'throw-forward',
  'throw-back',
  'special-neutral',
  'special-forward',
  'special-retreat',
  'special-air',
  'enhanced-special',
  'super',
  'auto-combo',
  'stone-armor',
  'passive-full',
  'trap-cut',
  'combo-escape',
  'combo-break',
  'momentum-reversal',
  'perfect-reversal',
  'hit-reaction-light',
  'hit-reaction-heavy',
  'launch-reaction',
  'block-reaction',
  'knockdown',
  'wake-up',
  'victory',
  'defeat',
] as const;

export type AnimationStateId = (typeof CHARACTER_ANIMATION_STATES)[number];

export const SHOWCASE_ANIMATION_STATES: readonly AnimationStateId[] = [
  'idle',
  'walk',
  'dash',
  'jump-rise',
  'landing',
  'light-1',
  'heavy-2',
  'perfect-block',
  'combo-break',
  'momentum-reversal',
  'hit-reaction-heavy',
  'knockdown',
  'wake-up',
  'victory',
];

const STATE_LABELS: Record<AnimationStateId, string> = {
  idle: 'Idle', walk: 'Walk', 'dash-start': 'Dash Start', dash: 'Dash',
  'dash-whiff': 'Dash Whiff', 'jump-start': 'Jump Start', 'jump-rise': 'Jump Rise',
  'jump-fall': 'Jump Fall', landing: 'Landing', crouch: 'Crouch', block: 'Block',
  'precise-block': 'Precise Block', 'perfect-block': 'Perfect Block',
  'light-1': 'Light 1', 'light-2': 'Light 2', 'light-3': 'Light 3',
  'heavy-1': 'Heavy 1', 'heavy-2': 'Heavy 2', 'heavy-3': 'Heavy 3',
  'low-light': 'Low Light', 'low-heavy': 'Low Heavy', 'air-light': 'Air Light',
  'air-heavy': 'Air Heavy', grab: 'Grab', 'throw-forward': 'Forward Throw',
  'throw-back': 'Back Throw', 'special-neutral': 'Special 1',
  'special-forward': 'Special 2', 'special-retreat': 'Special 3',
  'special-air': 'Air Special', 'enhanced-special': 'Enhanced Special', super: 'Super',
  'auto-combo': 'Auto Combo', 'stone-armor': 'Stone Armor',
  'passive-full': 'Passive Full', 'trap-cut': 'Trap Cut',
  'combo-escape': 'Combo Escape', 'combo-break': 'Combo Break',
  'momentum-reversal': 'Momentum Reversal', 'hit-reaction-light': 'Hit Light',
  'perfect-reversal': 'Perfect Reversal',
  'hit-reaction-heavy': 'Hit Heavy', 'launch-reaction': 'Launch Reaction',
  'block-reaction': 'Block Reaction', knockdown: 'Knockdown', 'wake-up': 'Wake Up',
  victory: 'Victory', defeat: 'Defeat',
};

export function animationStateLabel(state: AnimationStateId) {
  return STATE_LABELS[state];
}
