/**
 * Localization keys.
 *
 * Tutorial code never holds a sentence. A step carries a `TextKey`, and the
 * catalogues in `ru.ts` / `en.ts` carry the words. `tests/tutorial-i18n.test.mjs`
 * walks every course and fails if a key is missing from *either* locale, which
 * is what stops a lesson shipping with an empty instruction box.
 *
 * Keys are plain strings on purpose. A union type of ~700 literals would have to
 * be regenerated by hand on every authoring change, and the test already gives
 * the guarantee the union was meant to give.
 */

export type TextKey = string;

export type LocaleId = 'ru' | 'en';

export const LOCALES: readonly LocaleId[] = ['ru', 'en'];

/** Matches the existing UI, which is Russian. */
export const DEFAULT_LOCALE: LocaleId = 'ru';

export type TextCatalogue = Readonly<Record<TextKey, string>>;

/**
 * Values interpolated into a string, e.g. `{frames}` in
 * "You were {frames} frames early".
 */
export type TextValues = Readonly<Record<string, string | number>>;

const PLACEHOLDER = /\{(\w+)\}/g;

/**
 * Resolve a key, falling back to the default locale and then to the key itself.
 *
 * Returning the key rather than throwing matters: a missing string should make
 * a lesson look unfinished in the UI, never crash a player out of a step they
 * were halfway through. The test suite is where a missing key is meant to hurt.
 */
export function translate(
  catalogues: Readonly<Record<LocaleId, TextCatalogue>>,
  locale: LocaleId,
  key: TextKey,
  values: TextValues = {},
): string {
  const template = catalogues[locale][key]
    ?? catalogues[DEFAULT_LOCALE][key]
    ?? key;
  return interpolate(template, values);
}

export function interpolate(template: string, values: TextValues): string {
  return template.replace(PLACEHOLDER, (whole, name: string) => {
    const value = values[name];
    return value === undefined ? whole : String(value);
  });
}

/**
 * Build a key from its parts, so authoring cannot produce two spellings of the
 * same key. `stepKey('defense', 'standing-block', 'instruction')` →
 * `"tutorial.defense.standing-block.instruction"`.
 */
export function textKey(...parts: readonly string[]): TextKey {
  return ['tutorial', ...parts].join('.');
}
