import type { AiDifficulty, AiDifficultyProfile } from './types.js';

export const AI_DIFFICULTY_PROFILES: Readonly<
  Record<AiDifficulty, AiDifficultyProfile>
> = {
  easy: {
    reactionFrames: 18,
    decisionInterval: 12,
    neutralAttackPercent: 34,
    defensePercent: 35,
    guardPercent: 55,
    whiffPunishPercent: 20,
    errorPercent: 24,
    telegraphFrames: 24,
    comboTelegraphFrames: 12,
    punishTelegraphFrames: 18,
    comboDepth: 1,
    preferredMinimumDistance: 900,
    preferredMaximumDistance: 1_450,
    threatMargin: 100,
  },
  normal: {
    reactionFrames: 12,
    decisionInterval: 7,
    neutralAttackPercent: 58,
    defensePercent: 68,
    guardPercent: 75,
    whiffPunishPercent: 58,
    errorPercent: 8,
    telegraphFrames: 14,
    comboTelegraphFrames: 7,
    punishTelegraphFrames: 10,
    comboDepth: 3,
    preferredMinimumDistance: 750,
    preferredMaximumDistance: 1_300,
    threatMargin: 220,
  },
  hard: {
    reactionFrames: 7,
    decisionInterval: 3,
    neutralAttackPercent: 78,
    defensePercent: 92,
    guardPercent: 88,
    whiffPunishPercent: 90,
    errorPercent: 1,
    telegraphFrames: 6,
    comboTelegraphFrames: 3,
    punishTelegraphFrames: 4,
    comboDepth: 4,
    preferredMinimumDistance: 650,
    preferredMaximumDistance: 1_200,
    threatMargin: 350,
  },
  impossible: {
    reactionFrames: 4,
    decisionInterval: 2,
    neutralAttackPercent: 92,
    defensePercent: 98,
    guardPercent: 96,
    whiffPunishPercent: 99,
    errorPercent: 0,
    telegraphFrames: 4,
    comboTelegraphFrames: 2,
    punishTelegraphFrames: 3,
    comboDepth: 6,
    preferredMinimumDistance: 620,
    preferredMaximumDistance: 1_150,
    threatMargin: 430,
  },
  story: {
    reactionFrames: 9,
    decisionInterval: 5,
    neutralAttackPercent: 72,
    defensePercent: 82,
    guardPercent: 82,
    whiffPunishPercent: 76,
    errorPercent: 4,
    telegraphFrames: 9,
    comboTelegraphFrames: 5,
    punishTelegraphFrames: 7,
    comboDepth: 4,
    preferredMinimumDistance: 680,
    preferredMaximumDistance: 1_260,
    threatMargin: 300,
  },
};
